### ISSUE TITLE
Unable to get things working

### ISSUE THREAD

**Issue by IharAndreyeu** [grab/cocoapods-binary-cache#53]
Hello.

I am trying to adopt your plugin to my project and I've faced numerous issues.

At first, I was unable to install the plugin due to various ruby issues. Did manage to overcome those using info from [here](https://stackoverflow.com/questions/51126403/you-dont-have-write-permissions-for-the-library-ruby-gems-2-3-0-directory-ma) and [here](https://www.moncefbelyamani.com/the-definitive-guide-to-installing-ruby-gems-on-a-mac/#ruby-manager)

Then I've tried configuring the Podfile. And the first couple lines of code given in the [readme](https://github.com/grab/cocoapods-binary-cache/blob/master/docs/configure_cocoapods_binary_cache.md) got me totally confused. 

The below snippet is given as an example

```
config_cocoapods_binary_cache(
  cache_repo: {
    "default" => {
      "remote" => "git@cache_repo.git",
      "local" => "~/.cocoapods-binary-cache/prebuilt-frameworks-debug-config"
    },
    "test" => {
      "remote" => "git@another_cache_repo.git",
      "local" => "~/.cocoapods-binary-cache/prebuilt-frameworks-test-config"
    }
  }
)
```

My problem is that I have no idea of what `default` or `test` would mean and what should I add there. 

OK then. So I decided to check out the [example podfile](https://github.com/grab/cocoapods-binary-cache/blob/master/PodBinaryCacheExample/Podfile). I've copy-pasted the provided `config_cocoapods_binary_cache()` with my own remote and local repos addresses. But when I try 

`bundle exec pod install`

I get an error:

```
[!] Invalid 'Podfile' file: undefined method 'config_cocoapods_binary_cache' for #<Pod::Podfile:0x00007ffde3c12a80>.

 #  from /<#path_to_my_roject#>/Podfile:11
 #  -------------------------------------------
 #    plugin 'cocoapods-binary-cache'
 >    config_cocoapods_binary_cache(
 #      cache_repo: {
 #  -------------------------------------------
```

The same goes for another command provided in the readme:

```
CENSORED % bundle exec pod binary fetch
[!] Unknown command: `binary`
Did you mean: try?
```

Would you please be so kind to try to investigate into what am I doing wrong? Thanks

**Comment by trinhngocthuyen** [comment]
@IharAndreyeu Thanks for reaching out for help!

1/  About the failure you encountered, from what you described, my best guess is:
- You followed the declaration in the [example Podfile](https://github.com/grab/cocoapods-binary-cache/blob/master/PodBinaryCacheExample/Podfile) which only has this plugin enabled when the variable `IS_POD_BINARY_CACHE_ENABLED` is set as `true`.
- Since the plugin is not loaded because of the reason above, the `binary` is not recognized.

My recommendation to resolve the issue:
- Don't use the `is_pod_binary_cache_enabled` condition. The declaration should be just like this:
 ```rb
platform :ios, "10.0"

plugin "cocoapods-binary-cache"
config_cocoapods_binary_cache(
  ...
)
```
We shall remove the `is_pod_binary_cache_enabled` condition as it causes some confusion (It was used for a different purpose).

2/ About the `cache_repo` option, let me briefly explain it:
- Normally, you host the cached/prebuilt frameworks in a git repo. When we fetch the cache with the `pod binary fetch`, the cache will be fetched to your local. The two params in the `[:cache_repo]["default"]` correspond to the remote git repo and the local directory in which the git repo is fetched into.
- Depending on your infra setup, you may have multiple cache repos. For example, a cache repo is used for Debug configuration, another cache repo is used for QA build configuration. In that case, you can specify multiple cache repos:
```rb
config_cocoapods_binary_cache(
  cache_repo: {
    "repo1" => { ... },
    "repo2" => { ... },
    ...
  }
)
```
- The cache repo to use in the `fetch/push/prebuild` commands is specified by the `--repo` option. For example, `pod binary fetch --repo=repo1` will fetch cache from `repo1`. By default, if you don't specify this option, the repo will be chosen as the `"default"` section of the `cache_repo` config.

---
Hope the recommendation in (1) and the explanation in (2) help you resolve the issue.
We shall update the example project and the documentation accordingly to make the first-time setup less confusing.
Thanks for giving this plugin a try.
