### ISSUE TITLE
Support serveral swift version 

### ISSUE THREAD

**Issue by lixiaoyu** [grab/cocoapods-binary-cache#8]
Hi, is there a plan to support binary archived from different swift version?

In some cases,like evolution of swift or framework upgrade, we need to develop with different version of pod binary in parallel. While the cache repo only keeps the latest version, this can make  cache miss more often.
In some other case, if we need share binary between different projects,while pod version or swift version not always the same, how could we do with the pod binary storage in the logic of fetch and apply cache. Any advices?  

A question from a newbie, wish it's not a too naive question. :）
Best thanks

**Comment by bigbangvn** [comment]
@lixiaoyu It's a good question, if you only use swift >= 5.1.3 with module stability and library evolution turn on, then you will not need to rebuild your library for later swift version. But since our project still have mix of swift version, we haven't tested your case. Please let me know the result if you try it. Thanks!

**Comment by mohitpareek25** [comment]
Hi, @lixiaoyu / @bigbangvn is there any update regarding the support for the same ?
